// Input Messages

/* export const SET_CLIENT_STATUS_NOT_PLAYING = "SET_CLIENT_STATUS_NOT_PLAYING";
export const SET_CLIENT_STATUS_WAITING = "SET_CLIENT_STATUS_WAITING";
export const SET_CLIENT_STATUS_PLAYING = "SET_CLIENT_STATUS_PLAYING"; */

export const STACK_IN_PAIR_QUEUE = "STACK_IN_PAIR_QUEUE";
export const FREE_FROM_PAIR_QUEUE = "FREE_FROM_PAIR_QUEUE";
export const UNPAIR = "UNPAIR";
export const SEND_INFOS_TO_OPPONENT = "SEND_INFOS_TO_OPPONENT";
export const RECEIVE_OPPONENT_INFOS = "RECEIVE_OPPONENT_INFOS";

// Output Messages

export const START_PLAYING = "START_PLAYING";