// Input Messages

export const STACK_IN_PAIR_QUEUE = "STACK_IN_PAIR_QUEUE";
export const WAITING_SOLO_WORD_POOL = "WAITING_SOLO_WORD_POOL";
export const FREE_FROM_PAIR_QUEUE = "FREE_FROM_PAIR_QUEUE";
export const UNPAIR = "UNPAIR";
export const SET_CLIENT_PLAY_AGAIN = "SET_CLIENT_PLAY_AGAIN";
export const SEND_INFOS_TO_OPPONENT = "SEND_INFOS_TO_OPPONENT";

// Output Messages

export const START_PLAYING = "START_PLAYING";
export const ABORT_PLAY_AGAIN = "ABORT_PLAY_AGAIN";
export const WAIT_FOR_OPONNENT = "WAIT_FOR_OPONNENT";
export const FLASH_OPPONENT_DISCONNECTED = "FLASH_OPPONENT_DISCONNECTED";
export const RECEIVE_OPPONENT_INFOS = "RECEIVE_OPPONENT_INFOS";