export const SET_CLIENT_STATUS_NOT_PLAYING = "SET_CLIENT_STATUS_NOT_PLAYING";
export const SET_CLIENT_STATUS_WAITING = "SET_CLIENT_STATUS_WAITING";
export const SET_CLIENT_STATUS_PLAYING = "SET_CLIENT_STATUS_PLAYING";


export const PAIR_CLIENT = "PAIR_CLIENT";
export const FREE_CLIENT = "FREE_CLIENT";