export const SET_USER_INFOS = "SET_USER_INFOS";
export const SET_PSEUDO = "SET_PSEUDO";
export const SET_BEST_CHAIN = "SET_BEST_CHAIN";
export const INCREMENT_TYPOS = "INCREMENT_TYPOS";
export const SET_START_TIME = "SET_START_TIME";
export const SET_END_TIME = "SET_END_TIME";
export const SET_BEST_SPEED = "SET_BEST_SPEED";


export const SET_OPPONENT_INFOS = "SET_OPPONENT_INFOS";

export const SET_GAME_INFOS = "SET_GAME_INFOS";
export const SET_STATUS = "SET_STATUS";
export const SET_SPEED = "SET_SPEED";

export const INITIALIZE_CURRENT_GAME = "INITIALIZE_CURRENT_GAME";

export const ADD_WORD = "ADD_WORD";
export const DELETE_WORD = "DELETE_WORD";
export const DELETE_ALL_WORDS = "DELETE_ALL_WORDS";
export const INITIALIZE_WORDS = "INITIALIZE_WORDS";

export const SET_WORD_POOL = "SET_WORD_POOL";

export const ADJUST_LIFE = "ADJUST_LIFE";
export const INCREMENT_CHAIN = "INCREMENT_CHAIN";
export const RESET_CHAIN = "RESET_CHAIN";
export const INCREMENT_SCORE = "INCREMENT_SCORE";

export const SET_INPUT = "SET_INPUT";
export const RESET_INPUT = "RESET_INPUT";



